# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplugin.proto\x12\x06plugin\"\xa7\x01\n\rPluginRequest\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\x13\n\x0bplugin_data\x18\x02 \x01(\t\x12\x39\n\nparameters\x18\x03 \x03(\x0b\x32%.plugin.PluginRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"H\n\x0ePluginResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2O\n\rPluginService\x12>\n\rExecutePlugin\x12\x15.plugin.PluginRequest\x1a\x16.plugin.PluginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLUGINREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_PLUGINREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_PLUGINREQUEST']._serialized_start=25
  _globals['_PLUGINREQUEST']._serialized_end=192
  _globals['_PLUGINREQUEST_PARAMETERSENTRY']._serialized_start=143
  _globals['_PLUGINREQUEST_PARAMETERSENTRY']._serialized_end=192
  _globals['_PLUGINRESPONSE']._serialized_start=194
  _globals['_PLUGINRESPONSE']._serialized_end=266
  _globals['_PLUGINSERVICE']._serialized_start=268
  _globals['_PLUGINSERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
