# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14plugin_service.proto\x12\x06\x62\x61lorg\"9\n\rPluginRequest\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\x13\n\x0bplugin_data\x18\x02 \x01(\t\" \n\x0ePluginResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2Q\n\rPluginService\x12@\n\rExecutePlugin\x12\x15.balorg.PluginRequest\x1a\x16.balorg.PluginResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLUGINREQUEST']._serialized_start=32
  _globals['_PLUGINREQUEST']._serialized_end=89
  _globals['_PLUGINRESPONSE']._serialized_start=91
  _globals['_PLUGINRESPONSE']._serialized_end=123
  _globals['_PLUGINSERVICE']._serialized_start=125
  _globals['_PLUGINSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
