# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from balorg import plugin_service_pb2 as plugin__service__pb2


class PluginServiceStub(object):
    """Service definition for the Plugin Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePlugin = channel.unary_unary(
                '/balorg.PluginService/ExecutePlugin',
                request_serializer=plugin__service__pb2.PluginRequest.SerializeToString,
                response_deserializer=plugin__service__pb2.PluginResponse.FromString,
                )


class PluginServiceServicer(object):
    """Service definition for the Plugin Service
    """

    def ExecutePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePlugin,
                    request_deserializer=plugin__service__pb2.PluginRequest.FromString,
                    response_serializer=plugin__service__pb2.PluginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'balorg.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PluginService(object):
    """Service definition for the Plugin Service
    """

    @staticmethod
    def ExecutePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/balorg.PluginService/ExecutePlugin',
            plugin__service__pb2.PluginRequest.SerializeToString,
            plugin__service__pb2.PluginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
